import java.util.ArrayList;
import java.time.LocalDate;
class Amenity {
    private String name;

    public Amenity(String name) {
        this.name = name;
    }
}
















//public class Amenity { // Added 'public'
//    private String name;
//
//    public Amenity(String name) {
//        this.name = name;
//    }
//    
//    public String getName() { return name; } // Added Getter
//}
